sonar.organization=healthtracker-platform
sonar.projectKey=es.upm.miw:healthtracker-panel

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=.
